# Generated by Django 3.0.3 on 2020-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictations', '0002_dictation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('A', 'Advanced')], default='M', max_length=1),
        ),
    ]
