# Generated by Django 3.0.3 on 2020-06-05 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictations', '0006_dictation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='length',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
            preserve_default=False,
        ),
    ]
