# Generated by Django 3.0.3 on 2020-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='sample-slug', unique=True),
            preserve_default=False,
        ),
    ]
