# Generated by Django 3.0.3 on 2020-02-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='steno',
        ),
        migrations.AlterField(
            model_name='steno',
            name='steno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='lookup.Word'),
        ),
    ]
