# Generated by Django 3.0.3 on 2020-02-15 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steno',
            options={'ordering': ['steno']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='steno',
        ),
        migrations.AddField(
            model_name='steno',
            name='word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='lookup.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('R', 'Private'), ('P', 'Public')], default='P', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BriefList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('status', models.CharField(choices=[('R', 'Private'), ('P', 'Public')], default='P', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='steno',
            name='brief_list',
            field=models.ManyToManyField(to='lookup.BriefList'),
        ),
        migrations.AddField(
            model_name='steno',
            name='dictionary',
            field=models.ManyToManyField(to='lookup.Dictionary'),
        ),
        migrations.AddField(
            model_name='steno',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='lookup.Dictionary'),
        ),
    ]
