# Generated by Django 3.0.3 on 2020-02-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_auto_20200213_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='steno',
            name='word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='lookup.Word'),
        ),
        migrations.AlterField(
            model_name='steno',
            name='steno',
            field=models.CharField(max_length=50),
        ),
    ]
