# Generated by Django 3.0.3 on 2020-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_auto_20200605_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brieflist',
            name='status',
            field=models.CharField(choices=[('R', 'Private'), ('P', 'Public')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='status',
            field=models.CharField(choices=[('R', 'Private'), ('P', 'Public')], default='P', max_length=1),
        ),
    ]
